export enum AuthErrorCode {
    ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
    ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    SESSION_INVALID = 'SESSION_INVALID',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    PASSWORD_INVALID = 'PASSWORD_INVALID',
}
