import {
  user,
  success,
  xMark,
  mail,
  lock,
  eyeSlash,
  eye,
  arrowRight,
  userPlus,
  error,
  info,
  warning,
  check,
  envelope,
  sun,
  moon,
  paperAirplane,
  arrowLeft,
  link,
  key,
  shieldCheck,
  shieldExclamation,
  shield,
  userGroup,
  magnifyingGlassWebsite,
  chevronRight,
  shieldPlus,
  shieldUp,
  shieldUser,
  retry,
  server,
  funnel,
  funnelSlash,
  briefcase,
  crown,
  star,
  userCheck,
  grid,
  table,
  chevronUp,
  chevronUpDown,
  pause,
  pencil,
  trash,
  folderOpen,
  play,
  alertTriangle,
  checkCircle,
  chevronDown,
  code,
  document,
  documentDuplicate,
  documentText,
  download,
  tableCells,
  xCircle,
  chartBar,
  chartPie,
  chevronLeft,
  cog6Tooth,
  cpuChip,
  home,
  logout,
  userCircle,
  folder,
  reload,
  informationCircle,
} from './outline';

export const ICONS_CORE_OUTLINE = {
  'outline/user': user,
  'outline/success': success,
  'outline/x-mark': xMark,
  'outline/mail': mail,
  'outline/lock': lock,
  'outline/eye-slash': eyeSlash,
  'outline/eye': eye,
  'outline/arrow-right': arrowRight,
  'outline/user-plus': userPlus,
  'outline/error': error,
  'outline/info': info,
  'outline/warning': warning,
  'outline/check': check,
  'outline/envelope': envelope,
  'outline/sun': sun,
  'outline/moon': moon,
  'outline/paper-airplane': paperAirplane,
  'outline/link': link,
  'outline/arrow-left': arrowLeft,
  'outline/key': key,
  'outline/shield-check': shieldCheck,
  'outline/shield-exclamation': shieldExclamation,
  'outline/shield': shield,
  'outline/user-group': userGroup,
  'outline/magnifying-glass-website': magnifyingGlassWebsite,
  'outline/chevron-right': chevronRight,
  'outline/shield-up': shieldUp,
  'outline/shield-user': shieldUser,
  'outline/shield-plus': shieldPlus,
  'outline/retry': retry,
  'outline/server': server,
  'outline/funnel': funnel,
  'outline/funnel-slash': funnelSlash,
  'outline/user-check': userCheck,
  'outline/star': star,
  'outline/briefcase': briefcase,
  'outline/crown': crown,
  'outline/grid': grid,
  'outline/table': table,
  'outline/chevron-up': chevronUp,
  'outline/chevron-up-down': chevronUpDown,
  'outline/pause': pause,
  'outline/pencil': pencil,
  'outline/trash': trash,
  'outline/folder-open': folderOpen,
  'outline/play': play,
  'outline/alert-triangle': alertTriangle,
  'outline/check-circle': checkCircle,
  'outline/chevron-down': chevronDown,
  'outline/code': code,
  'outline/document': document,
  'outline/document-duplicate': documentDuplicate,
  'outline/document-text': documentText,
  'outline/download': download,
  'outline/table-cells': tableCells,
  'outline/x-circle': xCircle,
  'outline/chart-bar': chartBar,
  'outline/chart-pie': chartPie,
  'outline/chevron-left': chevronLeft,
  'outline/cog-6-tooth': cog6Tooth,
  'outline/cpu-chip': cpuChip,
  'outline/home': home,
  'outline/logout': logout,
  'outline/user-circle': userCircle,
  'outline/folder': folder,
  'outline/reload': reload,
  'outline/information-circle': informationCircle,
} as const;
