/**
 * Domain Event Processing Types
 *
 * @description
 * TypeScript type definitions and interfaces for Domain Event processing.
 * Provides type safety and contracts for the DomainEventProcessor service.
 *
 * @author MAD-AI Development Team
 * @version 1.0.0
 * @since 2024-08-18
 */

import type { DomainEvent } from '@domain/events/domain-event.entity';

/**
 * Interface that defines an Aggregate Root entity
 *
 * @description
 * Any entity that can generate Domain Events must implement this interface.
 * This ensures consistent API for event management across all aggregate roots.
 *
 * @example Entity implementation
 * ```typescript
 * export class User implements AggregateRoot {
 *   private _domainEvents: DomainEvent[] = [];
 *
 *   getDomainEvents(): DomainEvent[] {
 *     return [...this._domainEvents];
 *   }
 *
 *   clearDomainEvents(): void {
 *     this._domainEvents = [];
 *   }
 *
 *   private addDomainEvent(event: DomainEvent): void {
 *     this._domainEvents.push(event);
 *   }
 * }
 * ```
 */
export interface AggregateRoot {
    /**
     * Get all Domain Events generated by this aggregate
     *
     * @returns Array of Domain Events (should return copy, not reference)
     */
    getDomainEvents(): DomainEvent[];

    /**
     * Clear all Domain Events from this aggregate
     *
     * @description
     * This should be called after events are processed to prevent
     * memory leaks and duplicate event processing.
     */
    clearDomainEvents(): void;
}

/**
 * Metadata structure for Domain Events
 *
 * @description
 * Common metadata fields that can be attached to Domain Events
 * for additional context and audit information.
 */
export interface DomainEventMetadata {
    /** User ID associated with the event (if applicable) */
    userId?: number;

    /** User email for audit purposes */
    userEmail?: string;

    /** Username for display in logs */
    username?: string;

    /** Session ID for tracking user sessions */
    sessionId?: string;

    /** IP address of the user/request */
    ipAddress?: string;

    /** User agent string for web requests */
    userAgent?: string;

    /** Correlation ID for tracking related events */
    correlationId?: string;

    /** Request ID for tracing through systems */
    requestId?: string;

    /** Additional context data */
    [key: string]: unknown;
}

/**
 * Security event context for enhanced security logging
 *
 * @description
 * Additional context information for security-related events
 * to support forensic analysis and threat detection.
 */
export interface SecurityEventContext {
    /** Type of security event */
    eventCategory: SecurityEventCategory;

    /** Risk level assessment */
    riskLevel: SecurityRiskLevel;

    /** Source of the security event */
    source: SecurityEventSource;

    /** Additional security-specific metadata */
    securityMetadata?: SecurityMetadata;
}

/**
 * Categories for security events
 */
export type SecurityEventCategory =
    | 'Authentication'
    | 'Authorization'
    | 'Session Management'
    | 'Access Control'
    | 'Account Management'
    | 'Security Violation'
    | 'Data Access'
    | 'System Administration';

/**
 * Risk levels for security assessment
 */
export type SecurityRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Sources of security events
 */
export type SecurityEventSource =
    | 'User Action'
    | 'System Automatic'
    | 'Admin Action'
    | 'External Integration'
    | 'Security System'
    | 'Unknown';

/**
 * Security-specific metadata
 */
export interface SecurityMetadata {
    /** Number of attempts (for failed login, etc.) */
    attemptCount?: number;

    /** Time window for the attempts */
    timeWindow?: string;

    /** Source IP address */
    sourceIP?: string;

    /** Geographic location (if available) */
    geoLocation?: string;

    /** Device fingerprint */
    deviceId?: string;

    /** Browser/device information */
    deviceInfo?: string;

    /** Threat intelligence data */
    threatIndicators?: string[];

    /** Previous security events for this user/session */
    relatedEvents?: string[];
}

/**
 * Result of event processing operations
 */
export interface EventProcessingResult {
    /** Whether processing was successful */
    success: boolean;

    /** Number of events processed */
    eventsProcessed: number;

    /** Number of events that failed processing */
    eventsFailed: number;

    /** Processing duration in milliseconds */
    processingDuration: number;

    /** Any errors that occurred during processing */
    errors?: EventProcessingError[];
}

/**
 * Error information for failed event processing
 */
export interface EventProcessingError {
    /** ID of the event that failed */
    eventId: string;

    /** Type of the event that failed */
    eventType: string;

    /** Error message */
    message: string;

    /** Error stack trace (if available) */
    stack?: string;

    /** Timestamp when error occurred */
    timestamp: string;
}

/**
 * Configuration for event processing behavior
 */
export interface EventProcessingConfig {
    /** Whether to enable external system integration */
    enableExternalSystems: boolean;

    /** Whether to enable security event processing */
    enableSecurityProcessing: boolean;

    /** Whether to enable audit logging */
    enableAuditLogging: boolean;

    /** Maximum number of events to process in batch */
    maxBatchSize: number;

    /** Timeout for event processing in milliseconds */
    processingTimeout: number;

    /** Whether to fail fast on processing errors */
    failFast: boolean;
}

/**
 * Statistics for monitoring event processing performance
 */
export interface EventProcessingStats {
    /** Total events processed */
    totalEventsProcessed: number;

    /** Total events failed */
    totalEventsFailed: number;

    /** Average processing time per event */
    averageProcessingTime: number;

    /** Peak processing time */
    peakProcessingTime: number;

    /** Events processed by type */
    eventsByType: Record<string, number>;

    /** Events processed by severity */
    eventsBySeverity: Record<string, number>;

    /** Last processing timestamp */
    lastProcessedAt: string;
}

/**
 * Bulk operation result for processing multiple entities
 */
export interface BulkProcessingResult {
    /** Total entities processed */
    totalEntities: number;

    /** Entities processed successfully */
    successfulEntities: number;

    /** Entities that failed processing */
    failedEntities: number;

    /** Total events processed across all entities */
    totalEvents: number;

    /** Detailed results for each entity */
    entityResults: EntityProcessingResult[];

    /** Overall processing duration */
    totalDuration: number;
}

/**
 * Result for processing a single entity's events
 */
export interface EntityProcessingResult {
    /** Identifier for the entity (if available) */
    entityId?: string | number;

    /** Type of entity processed */
    entityType?: string;

    /** Whether entity processing was successful */
    success: boolean;

    /** Number of events from this entity */
    eventCount: number;

    /** Processing duration for this entity */
    duration: number;

    /** Error if processing failed */
    error?: string;
}

/**
 * Event filtering criteria for selective processing
 */
export interface EventFilter {
    /** Filter by event types */
    eventTypes?: string[];

    /** Filter by event severity */
    severities?: string[];

    /** Filter by date range */
    dateRange?: {
        from: Date;
        to: Date;
    };

    /** Filter by user ID */
    userId?: number;

    /** Filter by correlation ID */
    correlationId?: string;

    /** Custom filter function */
    customFilter?: (event: DomainEvent) => boolean;
}

/**
 * External system integration configuration
 */
export interface ExternalSystemConfig {
    /** Name of the external system */
    name: string;

    /** Whether this integration is enabled */
    enabled: boolean;

    /** Endpoint or connection information */
    endpoint?: string;

    /** Authentication configuration */
    authentication?: {
        type: 'api-key' | 'oauth' | 'basic' | 'none';
        credentials?: Record<string, string>;
    };

    /** Event types to send to this system */
    eventTypes?: string[];

    /** Minimum severity level to send */
    minimumSeverity?: string;

    /** Retry configuration */
    retryConfig?: {
        maxAttempts: number;
        backoffMs: number;
    };
}

/**
 * Audit trail entry for compliance and forensics
 */
export interface AuditTrailEntry {
    /** Unique audit entry ID */
    auditId: string;

    /** Related Domain Event ID */
    eventId: string;

    /** Type of the original event */
    eventType: string;

    /** When the audit entry was created */
    auditTimestamp: string;

    /** When the original event occurred */
    eventTimestamp: string;

    /** User who triggered the event */
    userId?: number;

    /** Action that was performed */
    action: string;

    /** Resource that was affected */
    resource?: string;

    /** Additional audit metadata */
    auditMetadata: Record<string, unknown>;

    /** Compliance tags */
    complianceTags?: string[];
}

/**
 * Type guard to check if an object implements AggregateRoot
 */
export function isAggregateRoot(obj: unknown): obj is AggregateRoot {
    return (
        typeof obj === 'object' &&
        obj !== null &&
        'getDomainEvents' in obj &&
        'clearDomainEvents' in obj &&
        typeof (obj as any).getDomainEvents === 'function' &&
        typeof (obj as any).clearDomainEvents === 'function'
    );
}

/**
 * Type guard to check if an event is security-related
 */
export function isSecurityEvent(event: DomainEvent): boolean {
    const securityEventTypes = [
        'USER_AUTHENTICATED',
        'USER_AUTHENTICATION_FAILED',
        'SESSION_TERMINATED',
        'SESSION_EXPIRED',
        'UNAUTHORIZED_ACCESS_ATTEMPTED',
        'SECURITY_VIOLATION_DETECTED',
        'USER_ACCOUNT_ACTIVATED',
        'USER_ACCOUNT_DEACTIVATED',
        'USER_ROLE_CHANGED',
    ];

    return (
        securityEventTypes.includes(event.eventType.toString()) ||
        event.severity.toString() === 'CRITICAL'
    );
}

/**
 * Utility type for entities that might have Domain Events
 */
export type MaybeAggregateRoot<T> = T & Partial<AggregateRoot>;

/**
 * Helper type for use case handlers that process events
 */
export type EventProcessingUseCase<TRequest, TResponse> = {
    execute(request: TRequest): Promise<TResponse>;
    processEvents?: boolean;
};
