import {
    user,
    success,
    xMark,
    mail,
    lock,
    eyeSlash,
    eye,
    arrowRight,
    userPlus,
    error,
    info,
    warning,
    check,
    envelope,
    sun,
    moon,
    paperAirplane,
    arrowLeft,
    link,
    key,
    shieldCheck,
    shieldExclamation,
    shield,
    userGroup,
    magnifyingGlassWebsite,
    chevronRight,
    shieldPlus,
    shieldUp,
    shieldUser,
} from './svg/outline';

export const ICONS_CORE_OUTLINE = {
    'outline/user': user,
    'outline/success': success,
    'outline/x-mark': xMark,
    'outline/mail': mail,
    'outline/lock': lock,
    'outline/eye-slash': eyeSlash,
    'outline/eye': eye,
    'outline/arrow-right': arrowRight,
    'outline/user-plus': userPlus,
    'outline/error': error,
    'outline/info': info,
    'outline/warning': warning,
    'outline/check': check,
    'outline/envelope': envelope,
    'outline/sun': sun,
    'outline/moon': moon,
    'outline/paper-airplane': paperAirplane,
    'outline/link': link,
    'outline/arrow-left': arrowLeft,
    'outline/key': key,
    'outline/shield-check': shieldCheck,
    'outline/shield-exclamation': shieldExclamation,
    'outline/shield': shield,
    'outline/user-group': userGroup,
    'outline/magnifying-glass-website': magnifyingGlassWebsite,
    'outline/chevron-right': chevronRight,
    'outline/shield-up': shieldUp,
    'outline/shield-user': shieldUser,
    'outline/shield-plus': shieldPlus,
} as const;
