import {
    user,
    success,
    arrowRight,
    lock,
    mail,
    error,
    info,
    warning,
    check,
    envelope,
    arrowLeft,
    login,
    link,
    checkCircle,
    loading,
    xCircle,
    trash,
    pause,
    play,
    home,
    bug,
} from './svg/filled';

export const ICONS_CORE_FILLED = {
    'filled/user': user,
    'filled/success': success,
    'filled/arrow-right': arrowRight,
    'filled/lock': lock,
    'filled/mail': mail,
    'filled/error': error,
    'filled/info': info,
    'filled/warning': warning,
    'filled/check': check,
    'filled/envelope': envelope,
    'filled/arrow-left': arrowLeft,
    'filled/login': login,
    'filled/link': link,
    'filled/check-circle': checkCircle,
    'filled/loading': loading,
    'filled/x-circle': xCircle,
    'filled/trash': trash,
    'filled/pause': pause,
    'filled/play': play,
    'filled/home': home,
    'filled/bug': bug,
} as const;
