/**
 * Domain Event Processor Service
 *
 * @description
 * Central service for processing Domain Events generated by Aggregate Roots.
 * Handles audit logging, external system integration, and event lifecycle management.
 *
 * @author MAD-AI Development Team
 * @version 1.0.0
 * @since 2024-08-18
 */

import { Injectable, Inject } from '@angular/core';
import { DomainEvent } from '@domain/events/domain-event.entity';
import type {
  AggregateRoot,
  EventProcessingResult,
  BulkProcessingResult,
  EntityProcessingResult,
  EventProcessingConfig,
} from '../types/domain-event-processing.types';
import { isAggregateRoot } from '../types/domain-event-processing.types';
import { EVENT_PROCESSING_CONFIG } from '@di/provide-domain-events';

/**
 * Service responsible for processing Domain Events from Aggregate Roots
 */
@Injectable({ providedIn: 'root' })
export class DomainEventProcessor {
  constructor(@Inject(EVENT_PROCESSING_CONFIG) private readonly config: EventProcessingConfig) {}

  /**
   * Process all Domain Events from an Aggregate Root entity
   */
  async processEntityEvents(entity: unknown): Promise<EventProcessingResult> {
    const startTime = Date.now();
    const result: EventProcessingResult = {
      success: true,
      eventsProcessed: 0,
      eventsFailed: 0,
      processingDuration: 0,
      errors: [],
    };

    try {
      // Check if entity is an aggregate root
      if (!entity || !isAggregateRoot(entity)) {
        result.processingDuration = Date.now() - startTime;
        return result;
      }

      // Extract events from entity
      const events = entity.getDomainEvents();

      if (events.length === 0) {
        result.processingDuration = Date.now() - startTime;
        return result;
      }

      console.info(`[DomainEventProcessor] Processing ${events.length} events from entity`);

      // Process all events
      for (const event of events) {
        try {
          await this.processIndividualEvent(event);
          result.eventsProcessed++;
        } catch (error) {
          console.error(`[DomainEventProcessor] Failed to process event ${event.id}:`, error);
          result.eventsFailed++;
          result.errors!.push({
            eventId: event.id,
            eventType: event.eventType.toString(),
            message: error instanceof Error ? error.message : String(error),
            timestamp: new Date().toISOString(),
          });

          if (this.config.failFast) {
            result.success = false;
            break;
          }
        }
      }

      // Clear events from entity
      entity.clearDomainEvents();

      // Final success determination
      result.success = result.eventsFailed === 0;
      result.processingDuration = Date.now() - startTime;

      console.info(
        `Domain Events Processing completed: ${result.eventsProcessed} processed, ${result.eventsFailed} failed`
      );

      return result;
    } catch (error) {
      console.error('[DomainEventProcessor] Critical error during event processing:', error);
      result.success = false;
      result.processingDuration = Date.now() - startTime;

      if (error instanceof Error) {
        result.errors!.push({
          eventId: 'unknown',
          eventType: 'PROCESSING_ERROR',
          message: error.message,
          stack: error.stack,
          timestamp: new Date().toISOString(),
        });
      }

      return result;
    }
  }

  /**
   * Process Domain Events from multiple entities (bulk operations)
   */
  async processBulkEntityEvents(entities: unknown[]): Promise<BulkProcessingResult> {
    const startTime = Date.now();
    const result: BulkProcessingResult = {
      totalEntities: entities.length,
      successfulEntities: 0,
      failedEntities: 0,
      totalEvents: 0,
      entityResults: [],
      totalDuration: 0,
    };

    if (entities.length === 0) {
      result.totalDuration = Date.now() - startTime;
      return result;
    }

    console.info(`[DomainEventProcessor] Processing ${entities.length} entities in bulk`);

    // Process all entities
    for (const entity of entities) {
      const entityStartTime = Date.now();
      let entityResult: EntityProcessingResult = {
        success: false,
        eventCount: 0,
        duration: 0,
      };

      try {
        const processingResult = await this.processEntityEvents(entity);

        entityResult = {
          success: processingResult.success,
          eventCount: processingResult.eventsProcessed,
          duration: Date.now() - entityStartTime,
        };

        if (processingResult.success) {
          result.successfulEntities++;
          result.totalEvents += processingResult.eventsProcessed;
        } else {
          result.failedEntities++;
          entityResult.error = processingResult.errors?.[0]?.message || 'Unknown error';
        }
      } catch (error) {
        result.failedEntities++;
        entityResult.error = error instanceof Error ? error.message : String(error);
        entityResult.duration = Date.now() - entityStartTime;
      }

      result.entityResults.push(entityResult);
    }

    result.totalDuration = Date.now() - startTime;

    console.info(
      `Bulk processing completed: ${result.successfulEntities}/${result.totalEntities} entities processed successfully`
    );

    return result;
  }

  /**
   * Process a single Domain Event
   */
  private async processIndividualEvent(event: DomainEvent): Promise<void> {
    try {
      console.info(`[DomainEventProcessor] Processing event: ${event.eventType}`);

      // Log the event for audit trail
      await this.logEvent(event);

      // Check if it's a security event for enhanced processing
      if (this.isSecurityEvent(event)) {
        await this.processSecurityEvent(event);
      }

      // Send to external systems if enabled
      if (this.config.enableExternalSystems) {
        await this.sendToExternalSystems(event);
      }

      console.info(`[DomainEventProcessor] Event ${event.eventType} processed successfully`);
    } catch (error) {
      console.error(`[DomainEventProcessor] Failed to process event ${event.eventType}:`, error);
      throw error;
    }
  }

  /**
   * Log Domain Event for audit trail
   */
  private async logEvent(event: DomainEvent): Promise<void> {
    if (!this.config.enableAuditLogging) {
      return;
    }

    const logEntry = {
      timestamp: new Date().toISOString(),
      eventId: event.id,
      eventType: event.eventType.toString(),
      severity: event.severity.toString(),
      occurredAt: event.occurredAt.value,
      eventData: event.eventData,
      source: 'MAD-AI-Domain',
      version: '1.0.0',
    };

    // Use structured logging for better parsing by log aggregators
    console.log(`[DOMAIN EVENT] ${event.eventType}:`, JSON.stringify(logEntry, null, 2));
  }

  /**
   * Determine if event is security-related
   */
  private isSecurityEvent(event: DomainEvent): boolean {
    const securityEventTypes = [
      'USER_AUTHENTICATED',
      'USER_AUTHENTICATION_FAILED',
      'SESSION_TERMINATED',
      'SESSION_EXPIRED',
      'UNAUTHORIZED_ACCESS_ATTEMPTED',
      'SECURITY_VIOLATION_DETECTED',
      'USER_ACCOUNT_ACTIVATED',
      'USER_ACCOUNT_DEACTIVATED',
      'USER_ROLE_CHANGED',
    ];

    return (
      securityEventTypes.includes(event.eventType.toString()) ||
      event.severity.toString() === 'CRITICAL'
    );
  }

  /**
   * Process security-critical events with enhanced logging
   */
  private async processSecurityEvent(event: DomainEvent): Promise<void> {
    if (!this.config.enableSecurityProcessing) {
      return;
    }

    const securityLogEntry = {
      timestamp: new Date().toISOString(),
      eventId: event.id,
      eventType: event.eventType.toString(),
      severity: event.severity.toString(),
      securityRelevance: 'HIGH',
      auditCategory: this.getSecurityAuditCategory(event.eventType.toString()),
      eventData: event.eventData,
      correlationId: this.generateCorrelationId(event),
    };

    // Enhanced security logging
    console.warn(`[SECURITY AUDIT] ${event.eventType}:`, JSON.stringify(securityLogEntry, null, 2));

    // For critical security events, consider real-time alerting
    if (event.severity.toString() === 'CRITICAL') {
      await this.handleCriticalSecurityEvent(event);
    }
  }

  /**
   * Send events to external monitoring systems
   */
  private async sendToExternalSystems(event: DomainEvent): Promise<void> {
    const externalPayload = {
      source: 'MAD-AI',
      eventType: event.eventType.toString(),
      severity: event.severity.toString(),
      timestamp: event.occurredAt.value,
      eventData: event.eventData,
      environment: 'production',
    };

    // Placeholder for external system integration
    console.log(
      `[EXTERNAL SYSTEMS] Sending event ${event.eventType} to monitoring systems:`,
      JSON.stringify(externalPayload, null, 2)
    );
  }

  /**
   * Handle critical security events with immediate attention
   */
  private async handleCriticalSecurityEvent(event: DomainEvent): Promise<void> {
    console.warn(`[CRITICAL SECURITY] ${event.eventType} detected:`, {
      eventId: event.id,
      timestamp: event.occurredAt.value,
      eventData: event.eventData,
    });
  }

  /**
   * Get security audit category for the event
   */
  private getSecurityAuditCategory(eventType: string): string {
    const categoryMap: Record<string, string> = {
      USER_AUTHENTICATED: 'Authentication',
      USER_AUTHENTICATION_FAILED: 'Authentication',
      SESSION_TERMINATED: 'Session Management',
      SESSION_EXPIRED: 'Session Management',
      UNAUTHORIZED_ACCESS_ATTEMPTED: 'Access Control',
      SECURITY_VIOLATION_DETECTED: 'Security Violation',
      USER_ACCOUNT_ACTIVATED: 'Account Management',
      USER_ACCOUNT_DEACTIVATED: 'Account Management',
      USER_ROLE_CHANGED: 'Authorization',
    };

    return categoryMap[eventType] || 'General';
  }

  /**
   * Generate correlation ID for event tracking
   */
  private generateCorrelationId(event: DomainEvent): string {
    // Simple correlation ID based on event metadata
    const userId = event.causedByUserId || 'unknown';
    const timestamp = event.occurredAt.value.slice(-8); // Last 8 chars of timestamp
    return `${userId}-${timestamp}`;
  }
}
