// application/errors/error-codes.enum.ts
export enum ApplicationErrorCode {
  // Auth feature
  AUTH_FAILED = 'AUTH_FAILED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  ALREADY_AUTHENTICATED = 'ALREADY_AUTHENTICATED',

  // User Management feature
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  INVALID_USER_STATE = 'INVALID_USER_STATE',
  USER_RETRIEVAL_FAILED = 'USER_RETRIEVAL_FAILED',

  // Role Management feature
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_ASSIGNMENT_FAILED = 'ROLE_ASSIGNMENT_FAILED',
  ROLE_IN_USE = 'ROLE_IN_USE',
  INVALID_ROLE_SPEC = 'INVALID_ROLE_SPEC',
  INVALID_ROLE_NAME = 'INVALID_ROLE_NAME',
  ROLE_NAME_TOO_LONG = 'ROLE_NAME_TOO_LONG',
  INVALID_ACCESS_LEVEL = 'INVALID_ACCESS_LEVEL',
  INVALID_ROLE_ID = 'INVALID_ROLE_ID',
  INVALID_ROLE_ID_FORMAT = 'INVALID_ROLE_ID_FORMAT',
  INVALID_SEARCH_FILTER = 'INVALID_SEARCH_FILTER',
  SEARCH_FILTER_TOO_LONG = 'SEARCH_FILTER_TOO_LONG',
  INVALID_ACTIVE_FILTER = 'INVALID_ACTIVE_FILTER',
  INVALID_LIMIT_FILTER = 'INVALID_LIMIT_FILTER',
  LIMIT_FILTER_TOO_HIGH = 'LIMIT_FILTER_TOO_HIGH',
  INVALID_FILTER_TYPE = 'INVALID_FILTER_TYPE',
  INVALID_SEARCH_TYPE = 'INVALID_SEARCH_TYPE',
  SEARCH_TOO_LONG = 'SEARCH_TOO_LONG',
  ROLE_LISTING_FAILED = 'ROLE_LISTING_FAILED',

  // System
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_INPUT = 'INVALID_INPUT',
  OPERATION_TIMEOUT = 'OPERATION_TIMEOUT',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
